### PR TITLE
fix: LoadingButton removed from nova core

### PR DESCRIPTION
**Pull request by alancolant**
This PR reintroduces the LoadingButton component, which was removed from the core of Laravel Nova since version 4.28.
 Its absence prevented the submission of the creation modal. 

This issue has been resolved by reintegrating the old component under a new name.

Fix issue #92

### CODE REVIEW

**Comment by ralphschindler** [comment]
This looks like a solid fix, thanks!

**Comment by JeffBeltran** [comment]
@alancolant if you can fix the commit message i'll get this merged asap, otherwise i will need to wait til after in the day when i get time. I really should add a contribution guide but... well time

**Comment by juanr-yes** [comment]
looking forward for this to be solved! thanks guys for the efforts

**Comment by juanr-yes** [comment]
hope this gets solved soon! thanks for the effort guys

**Comment by alancolant** [comment]
@JeffBeltran commit message updated

**Comment by galengidman** [comment]
This is currently a blocker for us - would love to see this merged soon. Thanks all!

**Comment by galengidman** [comment]
Thanks much @JeffBeltran and @alancolant

**Comment by JeffBeltran** [comment]
no problem, sorry it took me a bit to get it merged

**Pull request merged**
