### PR TITLE
add new expired date column

### PR DESCRIPTION
**Pull request by LucasLavallee**

### CODE REVIEW

**Comment by JeffBeltran** [comment]
Thanks @LucasLavallee i'll take a look at this but unless this is a feature supported by sanctum i'll prob not pull this in

**Comment by AndreSchwarzer** [comment]
Hey @JeffBeltran did you have a chance to look into this?

`expires_at` is native to Sanctum. Here is the [merged PR](https://github.com/laravel/sanctum/pull/252) and the [Upgrade Guide](https://github.com/laravel/sanctum/blob/3.x/UPGRADE.md).

**Comment by JeffBeltran** [comment]
oh man sorry @AndreSchwarzer i just realized i dropped the ball on this PR, let me look it over again and i'll get this implemented

**Comment by AndreSchwarzer** [comment]
Hi @JeffBeltran 

could you already finde some time to look into it? 

Thanks <3

**Comment by JeffBeltran** [comment]
I have added the column to the table view via #100 but i need to do some UI work before i can add the ability to set the expiration date. I'm going to close this for now since I have a plan to get this feature supported

**Pull request closed without merging**
