### PR TITLE
Add Ability To Define Token Abilities

### PR DESCRIPTION
**Pull request by craftyshaun**
Hi Jeff;

I have added a feature to define the ability of the token in the nova input form.

This simply takes a comma-separated string in the input box then splits & trims the input and provides to the `createToken()` function on the User Model.

I'm sorry but my code formatting tool was a bit liberal with its formating so you may want to run the commit through your tool of choice to fix the formatting.

If you want any changes please let me know

Cheers

Shaun

### CODE REVIEW

**Comment by craftyshaun** [comment]
@JeffBeltran I saw you had prettier in the dependencies so I ran it over the vue files and rebuilt for consistency.

If its not your tool of choice please just cherry-pick the commit.

**Comment by JeffBeltran** [comment]
yeah this looks great, didn't have a need for this myself but figured someone would eventually, let me pull this down on my lunch break and I'll likely pull this in.

**Comment by JeffBeltran** [comment]
Thanks Shaun, this is a nice add, One thing though to make this easy to track changes, could you submit this PR with just the two files that got changes? From a quick glance it should just be `CreateToken.vue` and `api.php` vs the 7 that are listed on this PR. If you need help just let me know.

**Comment by craftyshaun** [comment]
@JeffBeltran thanks for the feedback this is my first OSS PR so I'm a little green at this. 🤣

The files changed in the first commit (42269ebacb658b4213590b00c5e8da436228139a) were `CreateToken.vue`, `Tool.vue` and `api.php` I also ran an `npm prod` which I believe is needed to rebuild `tool.js` (i think) for when the tool is published has the changes cause the vue files are complied into `tool.js`.

The second commit (1fde1e2ed73142373266cb71b9201f935a327219) was just a prettier so could be removed and probably just made things worse. 

The issue I had was matching my formatting to yours so it created a nice diff. If you let me know what you use for code formatting I can revert my changes and make another PR. I'm assuming I just create a new PR and we'll close this one.

Thanks for your help and patience.

**Comment by JeffBeltran** [comment]
No worries, glad my little OSS could help, you'll be a pro in no time

yeah that is good, as i didn't notice all the changed files, in short you only want to add files to a PR if you actually needed to change them, when it comes to style (prettier) stuff i wouldn't worry about it, in the perfect world i would have set it up to make this step easier for you (that's my bad), but i honestly didn't expect anyone to open a PR lol.

I'd say for now we both learned a bit about this lol, i took another look and i don't see any issues with it, i was just trying to make it easy to track changes, i'll get this sorted for future requests/changes to make this easier. for now i'll merge this cause why not, and now you are no longer green haha

Thanks again for the PR

**Comment by JeffBeltran** [comment]
> I also ran an `npm prod` which I believe is needed to rebuild `tool.js` (i think) for when the tool is published has the changes cause the vue files are complied into `tool.js`.

just as an FYI, this is correct. When you run that command it will rebuild the required JS and it gets added to the /dist folder, which is what gets installed when you use composer. Ideally i should have this handled by the build server... but like i said i didn't expect anyone other than me to use this plugin lol

**Comment by JeffBeltran** [comment]
ah crap i forgot to tell you about how releases are created, doh...

I use semantic release to handle the versioning and releasing, this requires your commits to follow https://www.conventionalcommits.org/en/v1.0.0/ 

so since one of your commit messages wasn't `feat: add ability to define token abilities` this wasn't released, don't worry about this now but just wanted to point this out if you are wondering why this didn't release your changes

**Comment by craftyshaun** [comment]
Ahh sure does this mean packagist won't  bump as well. Currently I have your component cloned into a folder in my projector then hacker into my `composer.json`

It would be good it it could be bumped if that's the case then I can remove the hackery and default to packagist.

**Comment by JeffBeltran** [comment]
lol no worries, i should have caught it too as my day job is to review code ha, oh well. I'll push up a change later this week, i'll be busy next few days and won't get a chance, i'll ping you on the PR so you can see

**Pull request merged**
