### PR TITLE
Fix localization feature

### PR DESCRIPTION
**Pull request by hettiger**
- The lang path was hardcoded to be in the resource path which causes issues on newer Laravel instances
- Some localization strings were outdated / missing

### CODE REVIEW

**Comment by JeffBeltran** [comment]
Thanks @hettiger i'll review this and merge it later

**Comment by hettiger** [comment]
> Thanks @hettiger i'll review this and merge it later

Awesome! Thanks for looking into this so quickly. 😃

**Comment by hettiger** [comment]
> Thanks @hettiger i'll review this and merge it later

Awesome! Thanks for looking into this so quickly. 😃

**Comment by JeffBeltran** [comment]
i merged with with #88, had to create a new PR as i borked some git stuff. Thanks again for the contribution

**Pull request closed without merging**
